package remote

import (
	"crypto/subtle"
	"encoding/base64"
	"net/http"
	"strings"
)

const websocketAccessProtocolPrefix = "vulpine-key."

// Authenticator validates incoming connections.
type Authenticator struct {
	apiKey         string
	tokenValidator func(string) bool
}

// NewAuthenticator creates an authenticator with the given API key.
func NewAuthenticator(apiKey string) *Authenticator {
	return &Authenticator{apiKey: apiKey}
}

func (a *Authenticator) SetTokenValidator(fn func(string) bool) {
	a.tokenValidator = fn
}

// Validate checks the request for a valid API key.
// Accepts: Authorization: Bearer <key> header, ?token=<key> query param, or
// a websocket access subprotocol generated by AccessSubprotocol.
func (a *Authenticator) Validate(r *http.Request) bool {
	if a.apiKey == "" && a.tokenValidator == nil {
		return true // no auth configured
	}

	// Check Authorization header
	auth := r.Header.Get("Authorization")
	if len(auth) > 7 && auth[:7] == "Bearer " {
		token := auth[7:]
		if a.validateToken(token) {
			return true
		}
	}

	// Check query parameter
	token := r.URL.Query().Get("token")
	if token != "" && a.validateToken(token) {
		return true
	}

	if a.AcceptedWebSocketSubprotocol(r) != "" {
		return true
	}

	return false
}

func (a *Authenticator) validateToken(token string) bool {
	token = strings.TrimSpace(token)
	if token == "" {
		return false
	}
	if a.apiKey != "" && subtle.ConstantTimeCompare([]byte(token), []byte(a.apiKey)) == 1 {
		return true
	}
	if a.tokenValidator != nil && a.tokenValidator(token) {
		return true
	}
	return false
}

// AccessSubprotocol encodes an access key as an RFC6455-compatible websocket
// subprotocol token, keeping the key out of the websocket URL.
func AccessSubprotocol(apiKey string) string {
	if apiKey == "" {
		return ""
	}
	return websocketAccessProtocolPrefix + base64.RawURLEncoding.EncodeToString([]byte(apiKey))
}

// AcceptedWebSocketSubprotocol returns the matching access subprotocol, if any.
func (a *Authenticator) AcceptedWebSocketSubprotocol(r *http.Request) string {
	if (a.apiKey == "" && a.tokenValidator == nil) || r == nil {
		return ""
	}
	for _, header := range r.Header.Values("Sec-WebSocket-Protocol") {
		for _, raw := range strings.Split(header, ",") {
			protocol := strings.TrimSpace(raw)
			if protocol == "" || !strings.HasPrefix(protocol, websocketAccessProtocolPrefix) {
				continue
			}
			encoded := strings.TrimPrefix(protocol, websocketAccessProtocolPrefix)
			token, err := base64.RawURLEncoding.DecodeString(encoded)
			if err != nil {
				continue
			}
			if a.validateToken(string(token)) {
				return protocol
			}
		}
	}
	return ""
}
